name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x] # Use a specific Node.js version 

    steps:
    - uses: actions/checkout@v4 # Checkout the repository code
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4 # Configure the specified Node.js version
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies for faster installs
    - name: Install dependencies
      working-directory: ./frontend
      run: npm install # or 'npm ci' for clean installs with a lock file
    - name: Build project
      working-directory: ./frontend
      run: npm run build --if-present # Runs the build script if present in package.json
    #- name: Run tests
    #  run: npm test --if-present # Runs the test script if present in package.json
    #  working-directory: ./frontend
